package siks.utils;

import siks.models.CombinedItem;

import javax.print.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;

public class CombinedInvoicePrintBuilder {

    public static void printCombinedReport(List<CombinedItem> items) {
        try {
            if (items == null || items.isEmpty()) {
                System.out.println("✅ No combined data to print.");
                return;
            }

            // ---------------- Table measurements ----------------
            int pageWidth = 540;
            int rowHeight = 40;
            int headerHeight = 80;
            int footerHeight = 80;
            int startY = 50;

            // Calculate total height dynamically
            int totalHeight = headerHeight + footerHeight + (items.size() + 2) * rowHeight + 100;

            // ---------------- Create blank image ----------------
            BufferedImage img = new BufferedImage(pageWidth, totalHeight, BufferedImage.TYPE_INT_RGB);
            Graphics2D g = img.createGraphics();

            // Background white
            g.setColor(Color.WHITE);
            g.fillRect(0, 0, pageWidth, totalHeight);

            // Antialiasing for smooth text
            g.setRenderingHint(RenderingHints.KEY_TEXT_ANTIALIASING, RenderingHints.VALUE_TEXT_ANTIALIAS_ON);

            // Fonts
            java.awt.Font titleFont = new java.awt.Font("Algerian", java.awt.Font.BOLD, 38);
            java.awt.Font headerFont = new java.awt.Font("Noto Naskh Arabic", java.awt.Font.BOLD, 28);
            java.awt.Font rowFont = new java.awt.Font("Noto Naskh Arabic", java.awt.Font.PLAIN, 26);

            // Text color
            g.setColor(Color.BLACK);

            // ---------------- Draw Title ----------------
            g.setFont(titleFont);
            String title = "Combined Invoices Summary";

            FontMetrics fmTitle = g.getFontMetrics();
            int titleX = (pageWidth - fmTitle.stringWidth(title)) / 2;
            g.drawString(title, titleX, 50);

            // ---------------- Draw Table Header ----------------
            g.setFont(headerFont);
            int xItem = 40;
            int xCartons = 330;
            int xPieces = 430;

            int y = startY;

            g.drawRect(20, y - rowHeight + 10, pageWidth - 40, rowHeight); // header box
            g.drawString("Item", xItem, y);
            g.drawString("CTN", xCartons, y);
            g.drawString("PCS", xPieces, y);

            y += 10;

            // Draw separator line below header
            g.drawLine(20, y, pageWidth - 20, y);

            // ---------------- Draw Items ----------------
            g.setFont(rowFont);
            y += rowHeight;

            int totalCartons = 0;
            double totalPieces = 0;

            for (CombinedItem it : items) {
                String item = truncate(it.getItemName(), 18);
                int cartons = it.getTotalCartons();
                double pieces = it.getTotalPieces();

                g.drawString(item, xItem, y);
                g.drawString(String.valueOf(cartons), xCartons, y);
                g.drawString(String.format("%.0f", pieces), xPieces, y);

                // Row line
                g.drawLine(20, y + 10, pageWidth - 20, y + 10);

                totalCartons += cartons;
                totalPieces += pieces;
                y += rowHeight;
            }

            // ---------------- Totals Row ----------------
            g.setFont(headerFont);
            g.drawString("TOTAL", xItem, y);
            g.drawString(String.valueOf(totalCartons), xCartons, y);
            g.drawString(String.format("%.0f", totalPieces), xPieces, y);
            g.drawLine(20, y + 10, pageWidth - 20, y + 10);

            // ---------------- Footer ----------------
            g.setFont(rowFont);
            g.drawString("Generated by System", (pageWidth - 300) / 2, y + 60);

            // Column vertical lines
            g.setColor(Color.BLACK);
            int leftX = 20;
            int rightX = pageWidth - 20;
            g.drawLine(leftX, startY - rowHeight + 10, leftX, y + 10);        // left border
            g.drawLine(xCartons - 20, startY - rowHeight + 10, xCartons - 20, y + 10); // between Item and Cartons
            g.drawLine(xPieces - 20, startY - rowHeight + 10, xPieces - 20, y + 10);   // between Cartons and Pieces
            g.drawLine(rightX, startY - rowHeight + 10, rightX, y + 10);      // right border

            g.dispose();

            // ---------------- Convert to ESC/POS image bytes ----------------
            byte[] data = convertImageToEscPosBytes(img);

            // ---------------- Send to printer ----------------
            sendToThermalPrinter(data);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Helper: truncate item name
    private static String truncate(String text, int len) {
        return text.length() > len ? text.substring(0, len) : text;
    }

    // 🔸 Convert image to ESC/POS bytes (same helper logic as your POS)
    private static byte[] convertImageToEscPosBytes(BufferedImage img) throws Exception {
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        baos.write(new byte[]{0x1B, 0x40}); // init
        baos.write(EscPosImageHelper.convertImageToEscPos(img));
        baos.write(new byte[]{0x0A, 0x0A, 0x0A});
        // cut baos.write(new byte[]{0x1D, 'V', 1});
        return baos.toByteArray();
    }

    // 🔹 Send to printer
    private static void sendToThermalPrinter(byte[] data) {
        try {
            PrintService service = PrintServiceLookup.lookupDefaultPrintService();
            if (service == null) {
                System.out.println("⚠️ No printer found.");
                return;
            }

            DocPrintJob job = service.createPrintJob();
            DocFlavor flavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            Doc doc = new SimpleDoc(new ByteArrayInputStream(data), flavor, null);
            job.print(doc, null);

            System.out.println("🖨 Printed Combined Summary on: " + service.getName());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}