package siks.utils;

import siks.models.ItemCheckResult;

import javax.print.*;
import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.util.List;

public class OutOfStockPrintBuilder {

    public static void printReport(List<ItemCheckResult> items) {
        try {
            if (items == null || items.isEmpty()) {
                System.out.println("✅ No unavailable items to print.");
                return;
            }

            // ---------------- Header lines ----------------
            String title = "Out of Stock Items Report";
            String subTitle = "Generated by System";

            // ---------------- Table Data ----------------
            StringBuilder sb = new StringBuilder();
            sb.append(String.format("%-10s %-20s %-8s", "Invoice", "Item", "Stock")).append("\n");
            sb.append("----------------------------------------").append("\n");

            for (ItemCheckResult it : items) {
                String invoice = safe(it.getInvoiceId());
                String item = safe(it.getItemName());
                String stock = String.format("%.0f", it.getCurrentStock());

                if (item.length() > 18) item = item.substring(0, 18);

                sb.append(String.format("%-10s %-20s %-8s", invoice, item, stock)).append("\n");
            }

            sb.append("----------------------------------------").append("\n");

            // ---------------- Combine all sections into one block ----------------
            String reportText = title + "\n" + sb + subTitle;

            // ---------------- Build Image-based ESC/POS Bytes ----------------
            byte[] data = buildReceiptBytes(reportText);

            // ---------------- Send to printer ----------------
            sendToThermalPrinter(data);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // ---------------- Helper to avoid nulls ----------------
    private static String safe(String s) {
        return (s == null) ? "" : s.trim();
    }

    // ---------------- Image-based ESC/POS Byte Builder ----------------
    // ---------------- Build Image-based ESC/POS Byte Builder ----------------
    private static byte[] buildReceiptBytes(String reportText) throws Exception {
        int pageWidth = 540; // ~80mm printer width
        int lineHeight = 40;

        String[] lines = reportText.split("\n");
        int imageHeight = (lines.length * lineHeight) + 200;

        BufferedImage img = new BufferedImage(pageWidth, imageHeight, BufferedImage.TYPE_INT_RGB);
        Graphics2D g = img.createGraphics();

        // Background
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, pageWidth, imageHeight);
        g.setColor(Color.BLACK);

        // Fonts
        Font titleFont = new Font("Noto Naskh Arabic", Font.BOLD, 36);
        Font textFont = new Font("Noto Naskh Arabic", Font.PLAIN, 26);

        int y = 60;

        // ---------- Title ----------
        g.setFont(titleFont);
        String title = lines[0];
        FontMetrics fmTitle = g.getFontMetrics();
        int xTitle = (pageWidth - fmTitle.stringWidth(title)) / 2;
        g.drawString(title, xTitle, y);
        y += 60;

        // ---------- Table Header ----------
        g.setFont(textFont);
        FontMetrics fm = g.getFontMetrics();

        int colInvoice = 20;
        int colItem = 180;
        int colStock = 420;
        int rowHeight = 40;
        int tableWidth = 500;

        // Draw header row background
        g.setColor(new Color(230, 230, 230));
        g.fillRect(colInvoice - 5, y - 30, tableWidth, rowHeight + 10);
        g.setColor(Color.BLACK);

        // Header text
        g.drawRect(colInvoice - 5, y - 30, tableWidth, rowHeight + 10);
        g.drawString("Invoice", colInvoice, y);
        g.drawString("Item", colItem, y);
        g.drawString("Stock", colStock, y);

        y += rowHeight;

        // ---------- Draw table rows ----------
        for (int i = 2; i < lines.length - 1; i++) { // skip title + subtitle
            String line = lines[i].trim();
            if (line.isEmpty() || line.startsWith("-")) continue;

            String[] parts = line.split("\\s+");
            if (parts.length >= 3) {
                String invoice = parts[0];
                String item = parts[1];
                String stock = parts[parts.length - 1];

                // Draw rectangle for row
                g.drawRect(colInvoice - 5, y - 25, tableWidth, rowHeight);

                // Vertical column lines
                g.drawLine(colItem - 10, y - 25, colItem - 10, y + 15);
                g.drawLine(colStock - 20, y - 25, colStock - 20, y + 15);

                // Text inside cells
                g.drawString(invoice, colInvoice, y);
                g.drawString(item, colItem, y);
                g.drawString(stock, colStock, y);

                y += rowHeight;
            }
        }

        y += 50;
        g.drawString("Generated by System", colInvoice, y);

        g.dispose();

        // Convert image to ESC/POS bytes
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        baos.write(new byte[]{0x1B, 0x40});
        baos.write(EscPosImageHelper.convertImageToEscPos(img));
        baos.write(new byte[]{0x0A, 0x0A, 0x0A});
        baos.write(new byte[]{0x1D, 'V', 1});

        return baos.toByteArray();
    }
    // ---------------- Printer Sender ----------------
    private static void sendToThermalPrinter(byte[] data) {
        try {
            DocFlavor flavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            PrintService service = PrintServiceLookup.lookupDefaultPrintService();

            if (service == null) {
                System.out.println("⚠️ No default printer found!");
                return;
            }

            DocPrintJob job = service.createPrintJob();
            Doc doc = new SimpleDoc(new ByteArrayInputStream(data), flavor, null);
            job.print(doc, null);

            System.out.println("🖨 Printed successfully to: " + service.getName());

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
}